-- Create tables for External Media Booru

-- 1. Posts table
create table public.webapp_booru_1_posts (
  id bigint generated by default as identity primary key,
  source_url text not null,          -- The original page (e.g. twitter link)
  media_url text not null,           -- The direct image/video link
  preview_url text,                  -- Optional thumbnail link
  rating text default 'safe',        -- safe, questionnable, explicit
  width int,                         -- Optional dimensions
  height int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tags table
create table public.webapp_booru_1_tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text default 'general'        -- general, artist, copyright, character, meta
);

-- 3. Post Tags Junction table
create table public.webapp_booru_1_post_tags (
  post_id bigint references public.webapp_booru_1_posts(id) on delete cascade,
  tag_id bigint references public.webapp_booru_1_tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

-- Indexes for performance
create index idx_posts_created_at on public.webapp_booru_1_posts(created_at desc);
create index idx_tags_name on public.webapp_booru_1_tags(name);

-- RLS Policies (Open for now as per "beginner friendly" context, but good practice to define)
alter table public.webapp_booru_1_posts enable row level security;
alter table public.webapp_booru_1_tags enable row level security;
alter table public.webapp_booru_1_post_tags enable row level security;

-- Allow public read access
create policy "Public posts are viewable by everyone" on public.webapp_booru_1_posts for select using (true);
create policy "Public tags are viewable by everyone" on public.webapp_booru_1_tags for select using (true);
create policy "Public post_tags are viewable by everyone" on public.webapp_booru_1_post_tags for select using (true);

-- Allow anon insert (for demo purposes, usually you'd want auth)
create policy "Anyone can insert posts" on public.webapp_booru_1_posts for insert with check (true);
create policy "Anyone can insert tags" on public.webapp_booru_1_tags for insert with check (true);
create policy "Anyone can insert post_tags" on public.webapp_booru_1_post_tags for insert with check (true);

-- Allow anon update and delete (requires authentication)
create policy "Authenticated users can update posts" on public.webapp_booru_1_posts for update using (auth.uid() is not null);
create policy "Authenticated users can delete posts" on public.webapp_booru_1_posts for delete using (auth.uid() is not null);
create policy "Authenticated users can delete post_tags" on public.webapp_booru_1_post_tags for delete using (auth.uid() is not null);
